[package]
name = "mathr"
version = "0.1.0"
edition = "2021"

[dependencies]
libmapper-rs = {git = "ssh://git@github.com/EggAllocationService/libmapper-rs.git", rev = "6b2275c"}
meval = "0.2"
clap = {version = "4.0", features=["derive"]}